package deber_1;
import javax.swing.JOptionPane;

/**
 *
 * @author Dalton
 */
public class ejercicio_10 extends javax.swing.JFrame {

    /**
     * Creates new form Frm_E10_VentaPiezasTela
     */
    public ejercicio_10() {
        initComponents();
        n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de n"));
        setSize(385,375);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_nump = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_numc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        cb_nombrep = new javax.swing.JComboBox<>();
        b_ingresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        l_cont = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Venta de Telas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("N° Pieza: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        cb_nump.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "125", "986", "265" }));
        cb_nump.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_numpMouseClicked(evt);
            }
        });
        getContentPane().add(cb_nump, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 120, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Nombre Pieza:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("N° Clientes: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        getContentPane().add(txt_numc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 120, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Cantidad Piezas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 120, -1));

        cb_nombrep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tela algodon", "Tela fibra carbono", "Tela ankara" }));
        getContentPane().add(cb_nombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, -1));

        b_ingresar.setText("INGRESAR");
        b_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(b_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jButton2.setText("IMPRIMIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        l_cont.setText("...");
        getContentPane().add(l_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int n = 0, i = 1, numcliente, cantidad, talgodon, 
    tfcarbono, tankara, sta = 0, stfc = 0, stan = 0, asm, anp, menor;
    String nombrep, numpieza, numpta, numptfc, numptan, nombpta, nombptfc, nombptan, anps;
    //Tela algodon
    //Tela fibra carbono
    //Tela ankara
    public void ingresarDatos(){
        numpieza = cb_nump.getSelectedItem().toString();
        nombrep = cb_nombrep.getSelectedItem().toString();
        numcliente = Integer.parseInt(txt_numc.getText());
        cantidad = Integer.parseInt(txt_cantidad.getText());
        
        if(nombrep.equals("Tela algodon")){
            talgodon = talgodon + cantidad;
            numpta = numpieza;
            nombpta = nombrep;
            sta = sta + numcliente;
        }
        if(nombrep.equals("Tela fibra carbono")){
            tfcarbono = tfcarbono + cantidad;
            numptfc = numpieza;
            nombptfc = nombrep;
            stfc = stfc + numcliente;
        }
        if(nombrep.equals("Tela ankara")){
            tankara = tankara + cantidad;
            numptan = numpieza;
            nombptan = nombrep;
            stan = stan + numcliente;
        }
    }
   
    public void evalue(){
        if(sta < stfc){
            if(sta < stan){
                anps = numpta;
                anp = sta;
            }
            if(stan < sta){
                anps = numptan;
                anp = stan;
            }
        }
        if(stfc < sta){
            if(stfc < stan){
                anps = numptfc;
                anp = stfc;
            }
            if(stan < stfc){
                anps = numptan;
                anp = stan;
            }
        }
    }
    public void limpiar(){
        cb_nump.setSelectedIndex(0);
        cb_nombrep.setSelectedIndex(0);
        txt_numc.setText("");
        txt_cantidad.setText("");
        txt_numc.requestFocus();
    }
    
    public void imprimir(){
        JOptionPane.showMessageDialog(null, "Por cada número de pieza informar su nombre, su número, cuántos clientes la solicitaron y total de piezas vendidas: "+ "\n"+
                                            "N° Pieza: " + numpta +"\n"+
                                            "Nombre pieza: " + nombpta +"\n"+
                                            "Clientes: "+ sta +"\n"+
                                            "Total vendido: "+ talgodon+"\n"+
                                            "N° Pieza: " + numptfc +"\n"+
                                            "Nombre pieza: " + nombptfc +"\n"+
                                            "Clientes: "+ stfc +"\n"+
                                            "Total vendido: "+ tfcarbono+"\n"+
                                            "N° Pieza: " + numptan +"\n"+
                                            "Nombre pieza: " + nombptan +"\n"+
                                            "Clientes: "+ stan +"\n"+
                                            "Total vendido: "+ tankara+"\n");
        
        JOptionPane.showMessageDialog(null, "Informar cada uno de los números de piezas que fueron pedidas por más de 10 clientes: ");
        
        if(sta >= 10){
            JOptionPane.showMessageDialog(null,"N° Pieza: " + numpta +"\n"+
                                            "Clientes: "+ sta +"\n");
        }
        if(stfc >= 10){
            JOptionPane.showMessageDialog(null,"N° Pieza: " + numptfc +"\n"+
                                            "Clientes: "+ stfc +"\n");
        }
        if(stan >= 10){
            JOptionPane.showMessageDialog(null,"N° Pieza: " + numptan +"\n"+
                                            "Clientes: "+ stan +"\n");
        }
        
        
        JOptionPane.showMessageDialog(null, "Informar el número de pieza menos solicitada en total: "+ "\n"+
                                            "N° Pieza: " + anps +"\n"+
                                            "Clientes: "+ anp +"\n");
    }
    
    private void b_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ingresarActionPerformed
        if(i<=n){
            ingresarDatos();
            limpiar();
            l_cont.setText(i + " / " + n);
            if(i == n){
                cb_nombrep.setEnabled(false);
                cb_nump.setEnabled(false);
                txt_numc.setEnabled(false);
                txt_cantidad.setEnabled(false);
                b_ingresar.setEnabled(false);
                evalue();
            }
            i++;
        }
    }//GEN-LAST:event_b_ingresarActionPerformed

    private void cb_numpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_numpMouseClicked

    }//GEN-LAST:event_cb_numpMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        imprimir();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio_10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_ingresar;
    private javax.swing.JComboBox<String> cb_nombrep;
    private javax.swing.JComboBox<String> cb_nump;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l_cont;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_numc;
    // End of variables declaration//GEN-END:variables
}
