package Pruebas;

import javax.swing.JOptionPane;

/**
 *
 * @author Dalton
 */
public class Simulacro_prueba extends javax.swing.JFrame {

    /**
     * Creates new form Simulacro_prueba
     */
    public Simulacro_prueba() {
        initComponents();
        setLocationRelativeTo(this);
        n = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el número de registros que desea realizar"));
    }
    int n, costo_kw, consumo_kw, numero_usuario, aconsumo, aprovidencia, acambio, aretiro, anumero_usuario, aconsumo1, aconsumo2, aconsumo3 = 0;
    int i = 1;
    String tipo_usuario, zona, cedula, nombre_usuario, anombre_usuario = "";
    String mayor_zona = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_zona = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmb_tipo_usuario = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_costokw = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre_usuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_numero_usuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_consumokw = new javax.swing.JTextField();
        btn_ingresar2 = new javax.swing.JButton();
        btn_calcular = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_ingresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registros de usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 180, -1));

        jLabel2.setText("Zona");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));

        cmb_zona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Providencia", "Cambio", "Retiro" }));
        getContentPane().add(cmb_zona, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 100, -1));

        jLabel3.setText("Tipo de usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        cmb_tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comercial", "Particular" }));
        getContentPane().add(cmb_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 50, 100, -1));

        jLabel4.setText("Costo de Kw");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));
        getContentPane().add(txt_costokw, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, -1));

        jLabel5.setText("Nombre de usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, 10));
        getContentPane().add(txt_nombre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 130, 20));

        jLabel6.setText("Cedula");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, 10));
        getContentPane().add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 130, 20));

        jLabel7.setText("Número de usuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));
        getContentPane().add(txt_numero_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 30, -1));

        jLabel8.setText("Consumo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, 10));
        getContentPane().add(txt_consumokw, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 130, 20));

        btn_ingresar2.setText("Ingresar 2");
        btn_ingresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 20));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        jLabel9.setText(" ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 20, -1));

        btn_ingresar1.setText("Ingresar");
        btn_ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresar2ActionPerformed

        if (i <= n) {
            ingresar_datos1();
            jLabel9.setText(i + "/" + n);

            i++;

        }
    }//GEN-LAST:event_btn_ingresar2ActionPerformed

    private void btn_ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresar1ActionPerformed
        if (i <= n) {
            ingresar_datos1();
            jLabel9.setText(i + "/" + n);

            i++;

        }
    }//GEN-LAST:event_btn_ingresar1ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        imprimir();
    }//GEN-LAST:event_btn_calcularActionPerformed

    public void ingresar_datos1() {
        tipo_usuario = cmb_tipo_usuario.getSelectedItem().toString();
        zona = cmb_zona.getSelectedItem().toString();
        costo_kw = Integer.parseInt(txt_costokw.getText());
        if (consumo_kw > aconsumo) {
            aconsumo = consumo_kw;
            anombre_usuario = nombre_usuario;
            anumero_usuario = numero_usuario;
        }

        if (cmb_zona.equals("Providencia")&&(cmb_tipo_usuario.equals("Comercial"))) {
            aconsumo1 = aconsumo1 + consumo_kw;
            
                aprovidencia++;
        }
        if (cmb_zona.equals("Cambio")) {
            aconsumo2 = aconsumo2 + consumo_kw;
            if (cmb_tipo_usuario.equals("Comercial")) {
                acambio++;
            }
        }
        if (cmb_zona.equals("Retiro")) {
            aconsumo3 = aconsumo3 + consumo_kw;
            if (cmb_tipo_usuario.equals("Comercial")) {
                aretiro++;
            }
        }
        if (aprovidencia > acambio && aprovidencia > aretiro) {
            mayor_zona = "Providencia";
        }
        if (acambio > aprovidencia && acambio > aretiro) {
            mayor_zona = "Cambio";
        }
        if (aretiro > acambio && aretiro > aprovidencia) {
            mayor_zona = "Retiro";

        }
    }

    public void imprimir() {
        JOptionPane.showMessageDialog(null, "La zona con mayor cantidad de usuarios comerciales es " + mayor_zona);
    }

    public void ingresar_datos2() {
        tipo_usuario = cmb_tipo_usuario.getSelectedItem().toString();
        zona = cmb_zona.getSelectedItem().toString();
        numero_usuario = Integer.parseInt(txt_numero_usuario.getText());
        nombre_usuario = txt_nombre_usuario.getText();
        cedula = txt_cedula.getText();
        consumo_kw = Integer.parseInt(txt_consumokw.getText());

        if (cmb_zona.equals("Providencial")) {
            if (cmb_tipo_usuario.equals("Comercial")) {
                aprovidencia = aprovidencia++;
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese datos");
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulacro_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulacro_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulacro_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulacro_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulacro_prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_ingresar1;
    private javax.swing.JButton btn_ingresar2;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cmb_tipo_usuario;
    private javax.swing.JComboBox<String> cmb_zona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_consumokw;
    private javax.swing.JTextField txt_costokw;
    private javax.swing.JTextField txt_nombre_usuario;
    private javax.swing.JTextField txt_numero_usuario;
    // End of variables declaration//GEN-END:variables
}
