package main;
import tadarbolbinario.Arbol;
import tadarbolbinario.ArbolAVL;
import tadarbolbinario.ArbolBB;

public class Prueba {
	public static void main(String[] args) {
		ArbolAVL<Integer> avl1 = new ArbolAVL<Integer>("AVL1");
		ArbolBB<Integer> abb1 = new ArbolBB<Integer>("ABB1");
		long time;

		// Creacion AVL
		avl1.insertar(70);
		avl1.insertar(43);
		avl1.insertar(90);
		avl1.insertar(21);
		avl1.insertar(58);
		avl1.insertar(80);
		avl1.insertar(110);
		avl1.insertar(62);
		avl1.insertar(72);
		avl1.insertar(88);
		avl1.insertar(95);
		avl1.insertar(85);

		// Creacion ABB
		abb1.insertar(70);
		abb1.insertar(43);
		abb1.insertar(90);
		abb1.insertar(21);
		abb1.insertar(58);
		abb1.insertar(80);
		abb1.insertar(110);
		abb1.insertar(62);
		abb1.insertar(72);
		abb1.insertar(88);
		abb1.insertar(95);
		abb1.insertar(85);

		// Creacion AB
		Arbol<Integer> a85 = new Arbol<>(85);
		Arbol<Integer> a72 = new Arbol<>(72);
		Arbol<Integer> a62 = new Arbol<>(62);
		Arbol<Integer> a95 = new Arbol<>(95);
		Arbol<Integer> a21 = new Arbol<>(21);
		Arbol<Integer> a88 = new Arbol<>();
		Arbol<Integer> a58 = new Arbol<>();
		Arbol<Integer> a80 = new Arbol<>();
		Arbol<Integer> a110 = new Arbol<>();
		Arbol<Integer> a43 = new Arbol<>();
		Arbol<Integer> a90 = new Arbol<>();
		Arbol<Integer> ab1 = new Arbol<>();

		Arbol.juntar(a88, 88, a85, null);
		Arbol.juntar(a58, 58, null, a62);
		Arbol.juntar(a80, 80, a72, a88);
		Arbol.juntar(a110, 110, a95, null);
		Arbol.juntar(a43, 43, a21, a58);
		Arbol.juntar(a90, 90, a80, a110);
		Arbol.juntar(ab1, 70, a43, a90);
		ab1.setNombre("AB1");

		// Metodos AVL
		System.out.println("\n-----------------------------------ARBOL AVL---------------------------------------");
		time = System.nanoTime();
		System.out.println("Recorrido en PreOrder: ");
		avl1.preOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PreOrder en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en InOrder: ");
		avl1.inOrder();
		System.out.println("Tiempo de ejecucion del recorrido en InOrder en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en PostOrder: ");
		avl1.postOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PostOrder en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recrrido en Amplitud y niveles: ");
		avl1.listarAmplitudNiveles();
		System.out.println("Tiempo de ejecucion del recorrido en Amplitud en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de nodos del arbol AVL " + avl1.numeroDeNodos());
		System.out.println("Tiempo de conteo de nodos en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de hojas del arbol AVL " + avl1.numeroDeHojas());
		System.out.println("Tiempo de conteo de hojas AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Altura del arbol AVL " + avl1.altura());
		System.out.println("Tiempo de conteo de altura del arbol AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Menor del arbol AVL " + avl1.menor());
		System.out.println("Tiempo de busqueda del menor del arbol AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Mayor del arbol AVL " + avl1.mayor());
		System.out.println("Tiempo de busqueda del mayor del arbol AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Nivel del 85 en arbol AVL: " + avl1.nivel(85));
		System.out.println("Tiempo de conteo de altura del arbol para AVL: " + (System.nanoTime()-time));
		System.out.println("_____________________________________________________________________________________");

		// Metodos ABB
		System.out.println("\n----------------------------ARBOL BINARIO DE BUSQUEDA------------------------------");
		time = System.nanoTime();
		System.out.println("Recorrido en PreOrder: ");
		abb1.preOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PreOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en InOrder: ");
		abb1.inOrder();
		System.out.println("Tiempo de ejecucion del recorrido en InOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en PostOrder: ");
		abb1.postOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PostOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de nodos del arbol ABB " + abb1.numeroDeNodos());
		System.out.println("Tiempo de conteo de nodos en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de hojas del arbol ABB " + abb1.numeroDeHojas());
		System.out.println("Tiempo de conteo de hojas ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Altura del arbol ABB " + abb1.altura());
		System.out.println("Tiempo de conteo de altura del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Menor del arbol ABB " + abb1.menor());
		System.out.println("Tiempo de busqueda del menor del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Mayor del arbol ABB " + abb1.mayor());
		System.out.println("Tiempo de busqueda del mayor del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Nivel del 85 en arbol ABB: " + abb1.nivel(85));
		System.out.println("Tiempo de conteo de altura del arbol para ABB: " + (System.nanoTime()-time));
		System.out.println("_____________________________________________________________________________________");

		// Metodos AB
		System.out.println("\n-----------------------------------ARBOL BINARIO-----------------------------------");
		time = System.nanoTime();
		System.out.println("Recorrido en PreOrder: ");
		ab1.preOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PreOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en InOrder: ");
		ab1.inOrder();
		System.out.println("Tiempo de ejecucion del recorrido en InOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en PostOrder: ");
		ab1.postOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PostOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de nodos del arbol ABB " + ab1.numeroDeNodos());
		System.out.println("Tiempo de conteo de nodos en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de hojas del arbol ABB " + ab1.numeroDeHojas());
		System.out.println("Tiempo de conteo de hojas ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Altura del arbol ABB " + ab1.altura());
		System.out.println("Tiempo de conteo de altura del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Menor del arbol ABB " + ab1.menor());
		System.out.println("Tiempo de busqueda del menor del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Mayor del arbol ABB " + ab1.mayor());
		System.out.println("Tiempo de busqueda del mayor del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Nivel del 85 en arbol ABB: " + ab1.nivel(85));
		System.out.println("Tiempo de conteo de altura del arbol para ABB: " + (System.nanoTime()-time));
		System.out.println("_____________________________________________________________________________________");

		System.out.println("\nELIMANDO EL 21...........");
		avl1.eliminar(21);
		abb1.eliminar(21);
		ab1.eliminar(21);
		System.out.println("\nGENERANDO NUEVOS RESULTADOS......");

		// Metodos AVL
		System.out.println("\n------------------------------------ARBOL AVL--------------------------------------");
		time = System.nanoTime();
		System.out.println("Recorrido en PreOrder: ");
		avl1.preOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PreOrder en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en InOrder: ");
		avl1.inOrder();
		System.out.println("Tiempo de ejecucion del recorrido en InOrder en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en PostOrder: ");
		avl1.postOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PostOrder en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recrrido en Amplitud y niveles: ");
		avl1.listarAmplitudNiveles();
		System.out.println("Tiempo de ejecucion del recorrido en Amplitud en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de nodos del arbol AVL " + avl1.numeroDeNodos());
		System.out.println("Tiempo de conteo de nodos en AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de hojas del arbol AVL " + avl1.numeroDeHojas());
		System.out.println("Tiempo de conteo de hojas AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Altura del arbol AVL " + avl1.altura());
		System.out.println("Tiempo de conteo de altura del arbol AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Menor del arbol AVL " + avl1.menor());
		System.out.println("Tiempo de busqueda del menor del arbol AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Mayor del arbol AVL " + avl1.mayor());
		System.out.println("Tiempo de busqueda del mayor del arbol AVL " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Nivel del 85 en arbol AVL: " + avl1.nivel(85));
		System.out.println("Tiempo de conteo de altura del arbol para AVL: " + (System.nanoTime()-time));
		System.out.println("_____________________________________________________________________________________");

		// Metodos ABB
		System.out.println("\n----------------------------ARBOL BINARIO DE BUSQUEDA------------------------------");
		time = System.nanoTime();
		System.out.println("Recorrido en PreOrder: ");
		abb1.preOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PreOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en InOrder: ");
		abb1.inOrder();
		System.out.println("Tiempo de ejecucion del recorrido en InOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en PostOrder: ");
		abb1.postOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PostOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de nodos del arbol ABB " + abb1.numeroDeNodos());
		System.out.println("Tiempo de conteo de nodos en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de hojas del arbol ABB " + abb1.numeroDeHojas());
		System.out.println("Tiempo de conteo de hojas ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Altura del arbol ABB " + abb1.altura());
		System.out.println("Tiempo de conteo de altura del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Menor del arbol ABB " + abb1.menor());
		System.out.println("Tiempo de busqueda del menor del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Mayor del arbol ABB " + abb1.mayor());
		System.out.println("Tiempo de busqueda del mayor del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Nivel del 85 en arbol ABB: " + abb1.nivel(85));
		System.out.println("Tiempo de conteo de altura del arbol para ABB: " + (System.nanoTime()-time));
		System.out.println("_____________________________________________________________________________________");

		// Metodos AB
		System.out.println("\n------------------------------------ARBOL BINARIO----------------------------------");
		time = System.nanoTime();
		System.out.println("Recorrido en PreOrder: ");
		ab1.preOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PreOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en InOrder: ");
		ab1.inOrder();
		System.out.println("Tiempo de ejecucion del recorrido en InOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Recorrido en PostOrder: ");
		ab1.postOrder();
		System.out.println("Tiempo de ejecucion del recorrido en PostOrder en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de nodos del arbol ABB " + ab1.numeroDeNodos());
		System.out.println("Tiempo de conteo de nodos en ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Numero de hojas del arbol ABB " + ab1.numeroDeHojas());
		System.out.println("Tiempo de conteo de hojas ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Altura del arbol ABB " + ab1.altura());
		System.out.println("Tiempo de conteo de altura del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Menor del arbol ABB " + ab1.menor());
		System.out.println("Tiempo de busqueda del menor del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Mayor del arbol ABB " + ab1.mayor());
		System.out.println("Tiempo de busqueda del mayor del arbol ABB " + (System.nanoTime()-time));
		time = System.nanoTime();
		System.out.println("Nivel del 85 en arbol ABB: " + ab1.nivel(85));
		System.out.println("Tiempo de conteo de altura del arbol para ABB: " + (System.nanoTime()-time));
		System.out.println("_____________________________________________________________________________________");

	}
}